"""Shared pytest fixtures for the gateway test suite.

The gateway's adapters default to importing Openmail's
``SMTPManager`` and ``IMAPManager`` from the node package. Most
of the gateway tests do not need a live connection: they wire
in-memory transport callables instead. The fixtures here provide
the in-memory transports and a sample mapping.

The narada ids are generated by the real
``src.narada_identity.identity.generate_identity`` so the
mapping's regex (which requires the bech32m charset after
``narada1``) is satisfied.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest


# Make ``gateway`` and ``src.narada_identity`` importable.
# ``src`` is a PEP-420 namespace package; ``src`` must be reachable
# as a top-level package, so we add the directory that contains
# it (``node``) rather than ``node/src`` itself.
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(_REPO_ROOT))
sys.path.insert(0, str(_REPO_ROOT / "node"))


def _gen_narada_id(label: str) -> str:
    """Generate a real Narada public id with a deterministic label."""
    from src.narada_identity.identity import generate_identity
    from src.narada_identity.keystore import InMemoryKeystore

    keystore = InMemoryKeystore()
    identity, _ = generate_identity(label, keystore=keystore)
    return identity.public_id


@pytest.fixture(scope="session")
def alice_narada_id() -> str:
    return _gen_narada_id("alice@example.com")


@pytest.fixture(scope="session")
def bob_narada_id() -> str:
    return _gen_narada_id("bob@example.com")


@pytest.fixture
def narada_to_smtp(alice_narada_id, bob_narada_id) -> dict:
    return {
        alice_narada_id: "alice@example.com",
        bob_narada_id: "bob@example.com",
    }


@pytest.fixture
def smtp_to_narada(alice_narada_id, bob_narada_id) -> dict:
    return {
        "alice@example.com": alice_narada_id,
        "bob@example.com": bob_narada_id,
    }


@pytest.fixture
def mapping_file(tmp_path: Path, narada_to_smtp, smtp_to_narada) -> Path:
    payload = {
        "narada_to_smtp": narada_to_smtp,
        "smtp_to_narada": smtp_to_narada,
    }
    path = tmp_path / "mapping.json"
    path.write_bytes(
        json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    )
    return path


@pytest.fixture
def sample_body(alice_narada_id, bob_narada_id) -> dict:
    return {
        "subject": "hello",
        "sender": f"Alice <{alice_narada_id}>",
        "to": [bob_narada_id],
        "cc": [],
        "body_text": "hi bob",
        "sent_at": 1735689600,
    }


@pytest.fixture
def smtp_recorder():
    """A callable SMTP transport that records every sent message.

    Usage::

        sender = SmtpSender(transport=smtp_recorder)
        ...
        assert len(smtp_recorder.sent) == 1
    """
    sent: list = []

    def _transport(msg) -> tuple[bool, str]:
        sent.append(msg)
        return True, "250 OK"

    _transport.sent = sent  # type: ignore[attr-defined]
    return _transport


@pytest.fixture
def imap_recorder():
    """A callable IMAP fetch that records every fetched message.

    Usage::

        receiver = ImapReceiver(fetch=imap_recorder)
        ...
        assert len(imap_recorder.fetched) == 1
    """
    from email.message import EmailMessage

    fetched: list = []

    def _fetch() -> list[EmailMessage]:
        return list(fetched)

    _fetch.fetched = fetched  # type: ignore[attr-defined]
    return _fetch
